import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawn, spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { installProject } from "../../src/installer.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const bootstrap = ["core", "planning-bmad", "spec-council", "provisioning", "dashboard"];
async function project(name) {
  const target = await fs.mkdtemp(path.join(os.tmpdir(), `geki-runtime-${name}-`));
  await installProject({ target, requestedModules: bootstrap, tools: ["codex"] });
  return target;
}
const run = (target, script, args = []) => spawnSync(process.execPath, [path.join(target, ".geki", "runtime", script), ...args], { cwd: target, encoding: "utf8" });
async function approveStory(target, id, obligations = []) {
  const file = path.join(target, ".geki", "spec", "stories", `${id}.yaml`);
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, `id: "${id}"\nstatus: approved\ntestObligations: [${obligations.map((item) => `"${item}"`).join(", ")}]\n`);
  assert.equal(run(target, "contracts.mjs", ["approve", file]).status, 0);
}
async function approveEpic(target, id, stories, obligations = ["github"]) {
  const file = path.join(target, ".geki", "spec", "epics", `${id}.json`);
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, `${JSON.stringify({ schemaVersion: 1, id: String(id), status: "approved", stories, testObligations: obligations }, null, 2)}\n`);
  assert.equal(run(target, "contracts.mjs", ["approve", file]).status, 0);
}

test("execution requires approved readiness and explicit scope; repair stops at three", async () => {
  const target = await project("state");
  const git = (...args) => spawnSync("git", args, { cwd: target, encoding: "utf8" });
  assert.equal(git("init").status, 0);
  git("config", "user.email", "geki-test@example.invalid");
  git("config", "user.name", "Geki Test");
  git("add", "-A");
  assert.equal(git("commit", "-m", "fixture").status, 0);
  assert.equal(git("branch", "-M", "main").status, 0);
  let result = run(target, "state.mjs", ["start"]);
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /Explicit scope required/);
  const architectureFile = path.join(target, ".geki", "architecture.json");
  const stateFile = path.join(target, ".geki", "state", "current-run.json");
  const architecture = JSON.parse(await fs.readFile(architectureFile, "utf8"));
  architecture.status = "approved";
  await fs.writeFile(architectureFile, `${JSON.stringify(architecture, null, 2)}\n`);
  const state = JSON.parse(await fs.readFile(stateFile, "utf8"));
  state.phase = "ready";
  await fs.writeFile(stateFile, `${JSON.stringify(state, null, 2)}\n`);
  await approveStory(target, "1.1");
  await approveStory(target, "2.1");
  await approveEpic(target, "1", ["1.1"]);
  await approveEpic(target, "2", ["2.1"]);
  result = run(target, "state.mjs", ["start", "--epics", "1,2"]);
  assert.equal(result.status, 0, result.stderr);
  assert.equal(JSON.parse(result.stdout).currentStory, "1.1");
  assert.notEqual(run(target, "state.mjs", ["advance", "--story", "2.1"]).status, 0);
  const active = JSON.parse(await fs.readFile(stateFile, "utf8"));
  active.storyStatus["1.1"] = "integrated";
  await fs.writeFile(stateFile, `${JSON.stringify(active, null, 2)}\n`);
  assert.equal(run(target, "state.mjs", ["advance", "--story", "2.1"]).status, 0);
  assert.notEqual(run(target, "state.mjs", ["advance", "--story", "9.9"]).status, 0);
  for (let attempt = 1; attempt <= 3; attempt++) {
    result = run(target, "state.mjs", ["failure", "--signature", "build:CS1002:Program.cs"]);
    assert.equal(result.status, attempt === 3 ? 2 : 0);
  }
  const current = JSON.parse(await fs.readFile(stateFile, "utf8"));
  assert.equal(current.status, "needs-review");
  assert.equal(current.storyRepairAttempts["2.1"]["build:CS1002:Program.cs"], 3);
  result = run(target, "state.mjs", ["failure", "--signature", "build:CS1002:Program.cs"]);
  assert.equal(result.status, 2);
  result = run(target, "state.mjs", ["failure", "--signature", "different-signature"]);
  assert.equal(result.status, 2);
  const stillThree = JSON.parse(await fs.readFile(stateFile, "utf8"));
  assert.equal(stillThree.storyRepairAttempts["2.1"]["build:CS1002:Program.cs"], 3);
  assert.equal(stillThree.storyRepairAttempts["2.1"]["different-signature"], undefined);
  const reviewFile = path.join(target, ".geki", "evidence", "repair-review.json");
  await fs.mkdir(path.dirname(reviewFile), { recursive: true });
  const reviewedCommit = git("rev-parse", "HEAD").stdout.trim();
  await fs.writeFile(reviewFile, `${JSON.stringify({ kind: "repair-review", outcome: "passed", signature: "wrong", unresolvedHighCritical: 0, reviewerContextId: "reviewer-2", reviewedCommit, approvedStrategy: "inspect compiler diagnostics before changing code" })}\n`);
  assert.notEqual(run(target, "state.mjs", ["failure-clear", "--signature", "build:CS1002:Program.cs", "--evidence", reviewFile]).status, 0);
  await fs.writeFile(reviewFile, `${JSON.stringify({ kind: "repair-review", outcome: "passed", signature: "build:CS1002:Program.cs", unresolvedHighCritical: 0, reviewerContextId: "reviewer-2", reviewedCommit })}\n`);
  assert.notEqual(run(target, "state.mjs", ["failure-clear", "--signature", "build:CS1002:Program.cs", "--evidence", reviewFile]).status, 0);
  await fs.writeFile(reviewFile, `${JSON.stringify({ kind: "repair-review", outcome: "passed", signature: "build:CS1002:Program.cs", unresolvedHighCritical: 0, reviewerContextId: "reviewer-2", reviewedCommit, approvedStrategy: "inspect compiler diagnostics before changing code" })}\n`);
  assert.equal(run(target, "state.mjs", ["failure-clear", "--signature", "build:CS1002:Program.cs", "--evidence", reviewFile]).status, 0);
});

test("scope flags cannot be empty and passing evidence is hashed and revalidated", async () => {
  const target = await project("evidence");
  const git = (...args) => spawnSync("git", args, { cwd: target, encoding: "utf8" });
  assert.equal(git("init").status, 0);
  git("config", "user.email", "geki-test@example.invalid");
  git("config", "user.name", "Geki Test");
  git("add", "-A");
  assert.equal(git("commit", "-m", "fixture").status, 0);
  const architectureFile = path.join(target, ".geki", "architecture.json");
  const stateFile = path.join(target, ".geki", "state", "current-run.json");
  const architecture = JSON.parse(await fs.readFile(architectureFile, "utf8"));
  architecture.status = "approved";
  await fs.writeFile(architectureFile, `${JSON.stringify(architecture, null, 2)}\n`);
  const state = JSON.parse(await fs.readFile(stateFile, "utf8"));
  state.phase = "ready";
  await fs.writeFile(stateFile, `${JSON.stringify(state, null, 2)}\n`);
  await approveStory(target, "1.1", ["playwright"]);
  await fs.writeFile(path.join(target, ".geki", "gates.json"), `${JSON.stringify({ requiredEvidence: ["build"], conditionalEvidence: ["playwright"] })}\n`);
  assert.notEqual(run(target, "state.mjs", ["start", "--epics"]).status, 0);
  assert.equal(run(target, "state.mjs", ["start", "--stories", "1.1"]).status, 0);
  assert.notEqual(run(target, "state.mjs", ["gate", "--id", "build", "--outcome", "passed"]).status, 0);
  const evidence = path.join(target, ".geki", "evidence", "gates", "build.json");
  await fs.mkdir(path.dirname(evidence), { recursive: true });
  await fs.writeFile(evidence, "{\"passed\":true}\n");
  assert.notEqual(run(target, "state.mjs", ["gate", "--id", "build", "--outcome", "passed", "--evidence", evidence]).status, 0);
  const gateReport = (id) => ({ kind: "gate-report", scope: { story: "1.1", epic: null }, results: [{ id, outcome: "passed", exitCode: 0, command: `test ${id}`, startedAt: "2026-07-22T00:00:00.000Z", completedAt: "2026-07-22T00:00:01.000Z" }] });
  await fs.writeFile(evidence, `${JSON.stringify(gateReport("build"))}\n`);
  assert.equal(run(target, "state.mjs", ["gate", "--id", "build", "--outcome", "passed", "--evidence", evidence]).status, 0);
  const playwrightEvidence = path.join(target, ".geki", "evidence", "gates", "playwright.json");
  await fs.writeFile(playwrightEvidence, `${JSON.stringify(gateReport("playwright"))}\n`);
  assert.equal(run(target, "state.mjs", ["gate", "--id", "playwright", "--outcome", "passed", "--evidence", playwrightEvidence]).status, 0);
  const reviewEvidence = path.join(target, ".geki", "evidence", "review", "independent.json");
  await fs.mkdir(path.dirname(reviewEvidence), { recursive: true });
  await fs.writeFile(reviewEvidence, `${JSON.stringify({ kind: "independent-review", storyId: "1.1", gate: "independent-review", outcome: "passed", unresolvedHighCritical: 0, reviewerContextId: "clean-reviewer", reviewedCommit: "wrong" })}\n`);
  assert.notEqual(run(target, "state.mjs", ["gate", "--id", "independent-review", "--outcome", "passed", "--evidence", reviewEvidence]).status, 0);
  await fs.writeFile(reviewEvidence, `${JSON.stringify({ kind: "independent-review", storyId: "1.1", gate: "independent-review", outcome: "passed", unresolvedHighCritical: 0, reviewerContextId: "clean-reviewer", reviewedCommit: git("rev-parse", "HEAD").stdout.trim() })}\n`);
  assert.equal(run(target, "state.mjs", ["gate", "--id", "independent-review", "--outcome", "passed", "--evidence", reviewEvidence]).status, 0);
  assert.equal(run(target, "state.mjs", ["verify"]).status, 0);
  await fs.writeFile(path.join(target, "application-change.txt"), "changed after evidence\n");
  assert.notEqual(run(target, "state.mjs", ["verify"]).status, 0);
  await fs.unlink(path.join(target, "application-change.txt"));
  const storyContract = path.join(target, ".geki", "spec", "stories", "1.1.yaml");
  await fs.appendFile(storyContract, "changed: true\n");
  assert.equal(run(target, "contracts.mjs", ["approve", storyContract]).status, 0);
  assert.notEqual(run(target, "state.mjs", ["verify"]).status, 0);
  const reopened = JSON.parse(await fs.readFile(stateFile, "utf8"));
  assert.equal(reopened.phase, "spec-reopened");
});

test("two Stories isolate gates and Epic verification waits for both", async () => {
  const target = await project("two-story-epic");
  const git = (...args) => spawnSync("git", args, { cwd: target, encoding: "utf8" });
  assert.equal(git("init").status, 0);
  git("config", "user.email", "geki-test@example.invalid");
  git("config", "user.name", "Geki Test");
  git("add", "-A");
  assert.equal(git("commit", "-m", "fixture").status, 0);
  const architectureFile = path.join(target, ".geki", "architecture.json");
  const stateFile = path.join(target, ".geki", "state", "current-run.json");
  const architecture = JSON.parse(await fs.readFile(architectureFile, "utf8"));
  architecture.status = "approved";
  await fs.writeFile(architectureFile, `${JSON.stringify(architecture, null, 2)}\n`);
  const initialState = JSON.parse(await fs.readFile(stateFile, "utf8"));
  initialState.phase = "ready";
  await fs.writeFile(stateFile, `${JSON.stringify(initialState, null, 2)}\n`);
  await approveStory(target, "1.1", ["build"]);
  await approveStory(target, "1.2", ["build"]);
  await approveEpic(target, "1", ["1.1", "1.2"], []);
  await fs.writeFile(path.join(target, ".geki", "gates.json"), `${JSON.stringify({ requiredEvidence: [], conditionalEvidence: ["build", "github"] })}\n`);
  assert.equal(run(target, "state.mjs", ["start", "--epics", "1"]).status, 0);
  assert.equal(git("checkout", "-b", "epic/1").status, 0);
  assert.equal(run(target, "state.mjs", ["bind-epic", "--epic", "1", "--branch", "epic/1"]).status, 0);
  assert.equal(git("checkout", "-b", "story/1.1").status, 0);
  await fs.writeFile(path.join(target, "story-1.1.txt"), "Story 1.1 implementation\n");
  assert.equal(git("add", "story-1.1.txt").status, 0);
  assert.equal(git("commit", "-m", "story 1.1").status, 0);

  const gateDir = path.join(target, ".geki", "evidence", "gates");
  await fs.mkdir(gateDir, { recursive: true });
  const report = (story) => ({ kind: "gate-report", scope: { story, epic: "1" }, results: [{ id: "build", outcome: "passed", exitCode: 0, command: "dotnet build", startedAt: "2026-07-22T00:00:00.000Z", completedAt: "2026-07-22T00:00:01.000Z" }] });
  const firstEvidence = path.join(gateDir, "story-1.1.json");
  await fs.writeFile(firstEvidence, `${JSON.stringify(report("1.1"))}\n`);
  assert.equal(run(target, "state.mjs", ["gate", "--id", "build", "--outcome", "passed", "--evidence", firstEvidence]).status, 0);
  assert.equal(run(target, "state.mjs", ["verify", "--story", "1.1"]).status, 0);
  const firstStoryCommit = git("rev-parse", "HEAD").stdout.trim();
  assert.notEqual(run(target, "state.mjs", ["integrate", "--story", "1.1", "--commit", firstStoryCommit]).status, 0);
  assert.equal(git("checkout", "epic/1").status, 0);
  assert.equal(git("merge", "--no-ff", "story/1.1", "-m", "integrate story 1.1").status, 0);
  assert.equal(run(target, "state.mjs", ["integrate", "--story", "1.1", "--commit", firstStoryCommit]).status, 0);
  assert.equal(run(target, "state.mjs", ["advance", "--story", "1.2"]).status, 0);
  assert.equal(git("checkout", "-b", "story/1.2").status, 0);
  await fs.writeFile(path.join(target, "story-1.2.txt"), "Story 1.2 implementation\n");
  assert.equal(git("add", "story-1.2.txt").status, 0);
  assert.equal(git("commit", "-m", "story 1.2").status, 0);
  assert.notEqual(run(target, "state.mjs", ["gate", "--id", "build", "--outcome", "passed", "--evidence", firstEvidence]).status, 0);
  assert.notEqual(run(target, "state.mjs", ["verify", "--epic", "1"]).status, 0);

  const secondEvidence = path.join(gateDir, "story-1.2.json");
  await fs.writeFile(secondEvidence, `${JSON.stringify(report("1.2"))}\n`);
  assert.equal(run(target, "state.mjs", ["gate", "--id", "build", "--outcome", "passed", "--evidence", secondEvidence]).status, 0);
  assert.equal(run(target, "state.mjs", ["verify", "--story", "1.2"]).status, 0);
  const secondStoryCommit = git("rev-parse", "HEAD").stdout.trim();
  assert.equal(git("checkout", "epic/1").status, 0);
  assert.equal(git("merge", "--no-ff", "story/1.2", "-m", "integrate story 1.2").status, 0);
  assert.equal(run(target, "state.mjs", ["integrate", "--story", "1.2", "--commit", secondStoryCommit]).status, 0);
  const githubDir = path.join(target, ".geki", "evidence", "github");
  await fs.mkdir(githubDir, { recursive: true });
  const githubEvidence = path.join(githubDir, "epic-1.json");
  const epicHead = git("rev-parse", "HEAD").stdout.trim();
  await fs.writeFile(githubEvidence, `${JSON.stringify({ kind: "epic-github", epicId: "1", state: "MERGED", baseRefName: "coding", headRefOid: epicHead })}\n`);
  assert.notEqual(run(target, "state.mjs", ["gate", "--level", "epic", "--epic", "1", "--id", "github", "--outcome", "passed", "--evidence", githubEvidence]).status, 0);
  await fs.writeFile(githubEvidence, `${JSON.stringify({ kind: "epic-github", epicId: "1", state: "MERGED", baseRefName: "coding", headRefOid: epicHead, requiredChecks: [{ name: "CI", bucket: "pass" }], autoMergeRequest: { kind: "epic-auto-merge-request", headRefOid: epicHead } })}\n`);
  assert.equal(run(target, "state.mjs", ["gate", "--level", "epic", "--epic", "1", "--id", "github", "--outcome", "passed", "--evidence", githubEvidence]).status, 0);
  assert.equal(run(target, "state.mjs", ["verify", "--epic", "1"]).status, 0);
  const complete = JSON.parse(await fs.readFile(stateFile, "utf8"));
  assert.equal(complete.storyStatus["1.1"], "integrated");
  assert.equal(complete.storyStatus["1.2"], "integrated");
  assert.equal(complete.epicStatus["1"], "verified");
});

test("dashboard exposes GET state and rejects mutation methods", async (t) => {
  const target = await project("dashboard");
  const port = 43000 + Math.floor(Math.random() * 1000);
  const child = spawn(process.execPath, [path.join(target, ".geki", "runtime", "dashboard.mjs"), "--port", String(port)], { cwd: target, stdio: "ignore" });
  t.after(() => child.kill());
  let response;
  for (let i = 0; i < 30; i++) {
    try { response = await fetch(`http://127.0.0.1:${port}/api/state`); break; } catch { await new Promise((resolve) => setTimeout(resolve, 50)); }
  }
  assert.ok(response, "dashboard did not start");
  assert.equal(response.status, 200);
  const data = await response.json();
  assert.equal(data.state.phase, "planning");
  const denied = await fetch(`http://127.0.0.1:${port}/api/state`, { method: "POST" });
  assert.equal(denied.status, 405);
});

test("checkpoint and clean review packet persist cross-agent context", async () => {
  const target = await project("handoff");
  const git = (...args) => spawnSync("git", args, { cwd: target, encoding: "utf8" });
  assert.equal(git("init").status, 0);
  git("config", "user.email", "geki-test@example.invalid");
  git("config", "user.name", "Geki Test");
  git("add", "-A");
  assert.equal(git("commit", "-m", "fixture").status, 0);
  const secret = path.join(target, "secret.txt");
  await fs.writeFile(secret, 'api_key = "abcdefghijklmnopqrstuv"\n');
  const refused = run(target, "checkpoint.mjs", ["--agent", "codex"]);
  assert.notEqual(refused.status, 0);
  assert.match(refused.stderr, /Potential secret/);
  await fs.unlink(secret);
  const checkpoint = run(target, "checkpoint.mjs", ["--agent", "codex", "--next", "continue verification"]);
  assert.equal(checkpoint.status, 0, checkpoint.stderr);
  const handoff = await fs.readFile(path.join(target, ".geki", "handoff", "current.yaml"), "utf8");
  assert.match(handoff, /last_agent: "codex"/);
  const storyFile = path.join(target, ".geki", "spec", "stories", "1.1.yaml");
  await fs.mkdir(path.dirname(storyFile), { recursive: true });
  await fs.writeFile(storyFile, "id: 1.1\nstatus: approved\ntestObligations: []\n");
  const approved = run(target, "contracts.mjs", ["approve", storyFile]);
  assert.equal(approved.status, 0, approved.stderr);
  assert.equal(run(target, "contracts.mjs", ["verify", storyFile]).status, 0);
  const gateSource = path.join(target, ".geki", "evidence", "gates", "review-source.json");
  await fs.mkdir(path.dirname(gateSource), { recursive: true });
  await fs.writeFile(gateSource, `${JSON.stringify({ kind: "gate-report", scope: { story: "1.1" }, results: [{ id: "build", outcome: "passed", exitCode: 0, command: "dotnet build", startedAt: "2026-07-22T00:00:00.000Z", completedAt: "2026-07-22T00:00:01.000Z" }] })}\n`);
  const packetStateFile = path.join(target, ".geki", "state", "current-run.json");
  const packetState = JSON.parse(await fs.readFile(packetStateFile, "utf8"));
  packetState.storyGates = { "1.1": { build: { outcome: "passed", evidence: { path: ".geki/evidence/gates/review-source.json" } } } };
  await fs.writeFile(packetStateFile, `${JSON.stringify(packetState, null, 2)}\n`);
  const packet = run(target, "review-packet.mjs", ["--story", "1.1", "--base", "HEAD"]);
  assert.equal(packet.status, 0, packet.stderr);
  const reviewFile = path.join(target, ".geki", "review", "1.1.json");
  const review = JSON.parse(await fs.readFile(reviewFile, "utf8"));
  assert.equal(review.cleanContextRequired, true);
  assert.ok(review.git.head.length === 40);
  assert.ok(review.sources.storyContract.sha256.length === 64);
  assert.equal(review.sources.gates.length, 1);
  assert.equal(run(target, "review-packet.mjs", ["verify", reviewFile]).status, 0);
  const originalGateSource = await fs.readFile(gateSource, "utf8");
  await fs.appendFile(gateSource, " ");
  assert.notEqual(run(target, "review-packet.mjs", ["verify", reviewFile]).status, 0);
  await fs.writeFile(gateSource, originalGateSource);
  const originalPacket = await fs.readFile(reviewFile, "utf8");
  const tamperedPacket = JSON.parse(originalPacket);
  tamperedPacket.story = "9.9";
  await fs.writeFile(reviewFile, `${JSON.stringify(tamperedPacket, null, 2)}\n`);
  assert.notEqual(run(target, "review-packet.mjs", ["verify", reviewFile]).status, 0);
  await fs.writeFile(reviewFile, originalPacket);
  const dirtyApplication = path.join(target, "dirty-application.txt");
  await fs.writeFile(dirtyApplication, "not committed\n");
  assert.notEqual(run(target, "review-packet.mjs", ["verify", reviewFile]).status, 0);
  await fs.unlink(dirtyApplication);
  const committed = run(target, "checkpoint.mjs", ["--agent", "antigravity", "--commit", "--next", "review packet"]);
  assert.equal(committed.status, 0, committed.stderr);
  const atHead = git("show", "HEAD:.geki/handoff/current.yaml");
  assert.match(atHead.stdout, /checkpoint_commit: "SELF"/);
});

test("spec review packet binds a material artifact hash for a clean session", async () => {
  const target = await project("spec-review");
  const artifact = path.join(target, "_bmad-output", "prd.md");
  await fs.mkdir(path.dirname(artifact), { recursive: true });
  await fs.writeFile(artifact, "# PRD\n\nstatus: review\n");
  const result = run(target, "spec-review-packet.mjs", ["--artifact", artifact, "--lens", "security"]);
  assert.equal(result.status, 0, result.stderr);
  const output = result.stdout.trim();
  const packet = JSON.parse(await fs.readFile(path.join(target, output), "utf8"));
  assert.equal(packet.kind, "spec-review");
  assert.equal(packet.cleanContextRequired, true);
  assert.equal(packet.artifact.sha256.length, 64);
  assert.equal(packet.packetHash.length, 64);
  assert.equal(run(target, "spec-review-packet.mjs", ["verify", output]).status, 0);
  assert.notEqual(run(target, "spec-review-packet.mjs", ["--artifact", artifact, "--lens", "../../escape"]).status, 0);
  const packetFile = path.join(target, output);
  const originalPacket = await fs.readFile(packetFile, "utf8");
  const tamperedPacket = JSON.parse(originalPacket);
  tamperedPacket.lens = "product";
  await fs.writeFile(packetFile, `${JSON.stringify(tamperedPacket, null, 2)}\n`);
  assert.notEqual(run(target, "spec-review-packet.mjs", ["verify", output]).status, 0);
  await fs.writeFile(packetFile, originalPacket);
  await fs.appendFile(artifact, "changed\n");
  assert.notEqual(run(target, "spec-review-packet.mjs", ["verify", output]).status, 0);
});

test("spec review packet rejects Windows junctions that escape the project", { skip: process.platform !== "win32" }, async () => {
  const target = await project("junction");
  const outside = await fs.mkdtemp(path.join(os.tmpdir(), "geki-outside-"));
  await fs.writeFile(path.join(outside, "brief.md"), "# Outside\n");
  const linkedDirectory = path.join(target, "_bmad-output", "linked");
  await fs.mkdir(path.dirname(linkedDirectory), { recursive: true });
  await fs.symlink(outside, linkedDirectory, "junction");
  let result = run(target, "spec-review-packet.mjs", ["--artifact", path.join(linkedDirectory, "brief.md"), "--lens", "security"]);
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /real project boundary/);

  const localArtifact = path.join(target, "_bmad-output", "local.md");
  await fs.writeFile(localArtifact, "# Local\n");
  const outsideOutput = await fs.mkdtemp(path.join(os.tmpdir(), "geki-output-outside-"));
  await fs.symlink(outsideOutput, path.join(target, ".geki", "review"), "junction");
  result = run(target, "spec-review-packet.mjs", ["--artifact", localArtifact, "--lens", "security"]);
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /Review output ancestor escapes/);
});

test("review packets accept a Windows project path reached through a junction alias", { skip: process.platform !== "win32" }, async () => {
  const target = await project("junction-root");
  const aliasParent = await fs.mkdtemp(path.join(os.tmpdir(), "geki-alias-parent-"));
  const alias = path.join(aliasParent, "project-alias");
  await fs.symlink(target, alias, "junction");
  const artifact = path.join(alias, "_bmad-output", "prd.md");
  await fs.mkdir(path.dirname(artifact), { recursive: true });
  await fs.writeFile(artifact, "# PRD\n");
  const aliasedRun = (script, args = []) => spawnSync(process.execPath, [path.join(alias, ".geki", "runtime", script), ...args], { cwd: alias, encoding: "utf8" });
  const result = aliasedRun("spec-review-packet.mjs", ["--artifact", artifact, "--lens", "security"]);
  assert.equal(result.status, 0, result.stderr);
  assert.equal(aliasedRun("spec-review-packet.mjs", ["verify", result.stdout.trim()]).status, 0);
});
